### ISSUE TITLE
Unable to navigate to routes on Vercel deployments

### ISSUE THREAD

**Issue by andrewsrichardson** [alvarlagerlof/next-banner#70]
Hello,

![image](https://user-images.githubusercontent.com/52127531/161929714-c2ce4cb1-591b-4911-8cd4-d748922b046e.png)

I'm experiencing an issue with Vercel deployment. Evertything seems to work fine locally. The issue is not being able to navigate to the routes provided. 

I am using the latest version of React.

**Comment by alvarlagerlof** [comment]
Hmm, I have my sites deployed on Vercel too. Could you give me more information regarding your enviroment? Maybe the next.config.js and your build settings on Vercel. Thank you.

**Comment by alvarlagerlof** [comment]
That looks good to me. Do you have `.next/route-manifest.json` when you do a local build?

**Comment by andrewsrichardson** [comment]
Yep. The local build completes successfully, and `.next/route-manifest.json` has the correct routes inside as far as I can tell.

**Comment by alvarlagerlof** [comment]
There is an option called `nextDir` in the `nextBanner` object. You could change that.

**Comment by andrewsrichardson** [comment]
hmm. doing so sees the build error out quicker, as it seems to already be using the correct path to find the  `build-manifest.json`

![image](https://user-images.githubusercontent.com/52127531/162030839-a7bec0bc-5128-4fa2-acd7-f44f3b0b7238.png)

**Comment by alvarlagerlof** [comment]
Are you running npm/yarn build in the folder that has the .next?

**Comment by andrewsrichardson** [comment]
I assume that is where Vercel runs it from. when setting a root directory. 

![image](https://user-images.githubusercontent.com/52127531/162034680-24f06a5c-188c-441c-aa3c-8dcc8ef96c3f.png)

**Comment by alvarlagerlof** [comment]
I tried deploying the [example](https://github.com/alvarlagerlof/next-banner/tree/main/example) using only the Root Directory setting, and it [works](https://next-banner.vercel.app/). I have no idea what could cause this. Do you have anything more config-wise our could you provide a minimal repo that does not deploy on Vercel?

**Comment by andrewsrichardson** [comment]
To me, it seems like something in the next server is silently failing which is causing the navigation timeouts, and the `routes-manifest.json` error I think is a red herring. 

Does the next server load environment variables? I guess that would be more config that my project has, which the example project doesnt.

**Comment by alvarlagerlof** [comment]
It doesn't do anything special. Just a "next start". Have a look `[here](https://github.com/alvarlagerlof/next-banner/blob/f16b2a3664c8f1f7aa02fec65ad3e0356e9bed42/core/src/cli/runtime.ts#L63)`.

**Comment by andrewsrichardson** [comment]
The only thing I can think of is that the difference in path is throwing off 'next-start' so that it can't find the env variables in the correct place. But nothing I can see backs this up -- the server does not log if it has or has not found env variables and I cannot seem to find any way to change the log level

**Comment by alvarlagerlof** [comment]
I don't know how to test this without an example.

**Comment by andrewsrichardson** [comment]
Unfortuately I cant give my codebase. 

Another potential cause is the long loading time of the site in question. After all requests finish, 1min 53 sec has passed, which is longer than the current 30 sec timeout rule. Perhaps you could remove the timeout limit my passing `timeout: 0` to the `page.goto `function. Have you attempted to use this on any project that isnt a basic example? Sites with analytics or similar 3rd party reqs can have a long 'loading' time.

But I understand if you dont want to make changes without testing for an isolated example. I am not sure how I can replicate this in another repo.

**Comment by alvarlagerlof** [comment]
I understand you can not give out your codebase. It's hard to imagine what is wrong without examples though. I will try to add the timeout now and push a new version.

**Comment by alvarlagerlof** [comment]
Version [1.1.3](https://github.com/alvarlagerlof/next-banner/releases/tag/v1.1.3) is now out.

**Comment by andrewsrichardson** [comment]
Thanks!

This gave me some progress. I was getting timeout errors from a bug in the next version I was using. So after upgrading to the latest next version, I can now see the following `NODE_ENV` error:

![image](https://user-images.githubusercontent.com/52127531/162666141-43a00755-bd24-4e51-bae2-67b9b1bcd7eb.png)

The completion of the build is waiting for the result of the  postbuild command. It times out as the server is never run successfully I believe, but I cant tell for certain with the current log level. I can see the server fails, but it does not close the command. 

Perhaps, using your example, you could add more logs to see what env vars are used when running from a subdir? And hopefully we can learn more about why the server fails in this case.

As a side note, id like to help debug this myself, but I am unsure about how you are running this locally? My cli outputs nothing when I run the package on my machine 
![image](https://user-images.githubusercontent.com/52127531/162667128-e642cac4-9a26-498f-8fec-45375af1aba2.png)

**Comment by alvarlagerlof** [comment]
Okay, some progress. This is not an npx command. So just running `npm run next-banner `is the correct command. What Node version is your Vercel CI on? Mine is on 14. I could think about adding more logs, but getting it to run locally first should be attempted first I think. I thought that was already working?

**Comment by andrewsrichardson** [comment]
Apologies - that screenshot was me trying to get it running straight from `node_modules`. This is the output of my attempts to run locally: 

![image](https://user-images.githubusercontent.com/52127531/162755279-a1d5ad10-e984-4062-bb7e-7dd05803549d.png)

It has not yet been running locally for me, no. The tests I've been doing have been using the Vercel CLI & attempts at deploying.

My Vercel Node version is also on 14.

**Comment by alvarlagerlof** [comment]
Ah right, just npm run build, locally. That should run build and postbuild. Build is needed first for the cli to have an output to work on.

**Comment by andrewsrichardson** [comment]
Sorry, again I should have been more clear. That's what I have been doing and have had the same result.

![image](https://user-images.githubusercontent.com/52127531/162868263-b62f48d4-824b-488b-9005-d33cec338889.png)

**Comment by alvarlagerlof** [comment]
Wow, it doesn't output anything at all? I feel like at least [this](https://github.com/alvarlagerlof/next-banner/blob/fed72f4a3177a1f346f054ce1e9a9c2e9aebc7bb/core/src/cli/index.ts#L16) should show up. it doesn't?

**Comment by andrewsrichardson** [comment]
nope. Even with `--verbose` the output is nothing. It might worth pointing out I am on a windows machine.

**Comment by alvarlagerlof** [comment]
Do you think you have any chance to test in WSL? I don't have any windows machine to test with myself.

**Comment by alvarlagerlof** [comment]
This is fixed in version [v1.1.4](https://github.com/alvarlagerlof/next-banner/releases/tag/v1.1.4). The issue turned out to be errors being silenced plus node `spawn()` not working the same on Windows. I replaced it with the `spawn()` function in [cross-spawn](https://www.npmjs.com/package/cross-spawn).
