### ISSUE TITLE
documentation: README example for custom post layout is incorrect

### ISSUE THREAD

**Issue by jariz** [alvarlagerlof/next-banner#83]
The `pages/next-banner-layouts/post.jsx` example in the readme is incorrect.
The part where it references useBannerData is currently:

````
  const {
    title = "Placeholder title",
    description = "Placeholder description"
  } = useBannerData();
````

while it should be...
```
  const {
    meta: { title = "Placeholder title", description = "Placeholder description" },
  } = useBannerData();
```

**Comment by alvarlagerlof** [comment]
Thanks! Fixed in https://github.com/alvarlagerlof/next-banner/commit/e57df59e5d670b69a81f36b75dfe931bdc607695
